name: Publish Dumpify

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.2.3)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore ./src

    - name: Build
      run: dotnet build ./src -c Release --no-restore

    - name: Create Nuget Package
      run: dotnet pack -c Release /p:Version=${{ github.event.inputs.version }} /p:PackageReleaseNotes="See https://github.com/MoaidHathot/Dumpify/releases/tag/${{ github.event.inputs.version }}" ./src/Dumpify

    - name: Archive Nuget Package for Dumpify
      uses: actions/upload-artifact@v4
      with:
        name: packages
        path: "./src/Dumpify/bin/Release/Dumpify.${{ github.event.inputs.version }}.nupkg"

    - name: Publish NuGet Package to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet nuget push "./src/Dumpify/bin/Release/Dumpify.${{ github.event.inputs.version }}.nupkg" --api-key $GITHUB_TOKEN --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
